### ISSUE TITLE
IDH and 1p/19q labels for CPTAC/Rembrandt/Brain Tumor Progression datasets

### ISSUE THREAD

**Issue by satrajitgithub** [Svdvoort/PrognosAIs_glioma#1]
Hi Sebastian,

Congrats on the great work! 

I wanted to know if you could use the data from CPTAC/Rembrandt/Brain Tumor Progression datasets for IDH and 1p/19q as they do not seem to have this information (as they are marked by -1 in your csv: https://github.com/Svdvoort/PrognosAIs_glioma/blob/master/Supplementary_data/included_patient_labels.csv )

Thanks

**Comment by Svdvoort** [comment]
Hi,

Unfortunately, I don't have this data. It was not available at the time of our study, and I think it's still not available now. 
I refer you to the original data publications, perhaps you can contact them to see if they intend to open up the data in the future: 

- CPTAC: https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=30671232
- Rembrandt: https://wiki.cancerimagingarchive.net/display/Public/REMBRANDT
- Brain Tumor Progression: https://wiki.cancerimagingarchive.net/display/Public/Brain-Tumor-Progression
